"""enforce monetary constraints

Revision ID: 43b1e3d41169
Revises: 3048db882ff3
Create Date: 2026-08-31 03:03:07.886429
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '43b1e3d41169'
down_revision: Union[str, Sequence[str], None] = '3048db882ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_attribution_recovered_nonnegative', 'attribution_records', 'recovered_amount >= 0')
    op.create_check_constraint('ck_obligations_amount_nonnegative', 'obligations', 'amount_at_risk >= 0')
    op.create_check_constraint('ck_obligations_currency_code', 'obligations', 'length(currency) = 3')
    op.create_check_constraint('ck_payment_attempts_amount_nonnegative', 'payment_attempts', 'amount >= 0')
    op.create_check_constraint('ck_payment_attempts_currency_code', 'payment_attempts', 'length(currency) = 3')
    op.create_check_constraint('ck_actions_cost_nonnegative', 'recovery_actions', 'cost_minor_units >= 0')
    op.create_check_constraint('ck_cases_currency_code', 'recovery_cases', 'length(currency) = 3')
    op.create_check_constraint('ck_cases_recovered_amount_nonnegative', 'recovery_cases', 'recovered_amount >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_cases_recovered_amount_nonnegative', 'recovery_cases', type_='check')
    op.drop_constraint('ck_cases_currency_code', 'recovery_cases', type_='check')
    op.drop_constraint('ck_actions_cost_nonnegative', 'recovery_actions', type_='check')
    op.drop_constraint('ck_payment_attempts_currency_code', 'payment_attempts', type_='check')
    op.drop_constraint('ck_payment_attempts_amount_nonnegative', 'payment_attempts', type_='check')
    op.drop_constraint('ck_obligations_currency_code', 'obligations', type_='check')
    op.drop_constraint('ck_obligations_amount_nonnegative', 'obligations', type_='check')
    op.drop_constraint('ck_attribution_recovered_nonnegative', 'attribution_records', type_='check')
    # ### end Alembic commands ###
